package preprocessing;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class SimilarWords{


   public static List<String> shortCurrency = Arrays.asList("$", "€", "¢", "£", "¥", "zl", "%");
    public static List<String> currencySymbol = Arrays.asList("usd", "eur", "crc", "gbp", "jpy", "pln", "per");
    public static List<String> Currency = Arrays.asList("usa dolar", "euro", "costa rican colón", "british pound sterling", "japanese yen", "polish zloty",
            "percent");

    public static List<String> currencyNames = Arrays.asList("AED", "AFN", "ALL", "AFN", "ARS", "AWG", "AUD", "AZN", "BSD", "BBD", "BDT", "BYR", "BZD",
            "BMD", "BOB", "BAM", "BWP", "BGN", "BRL", "BND", "KHR", "CAD", "KYD", "CLP", "CNY", "COP",
            "CRC", "HRK", "CUP", "CZK", "DKK", "DOP", "XCD", "EGP", "SVC", "EEK", "EUR", "FKP", "FJD",
            "GHC", "GIP", "GTQ", "GGP", "GYD", "HNL", "HKD", "HUF", "ISK", "INR", "IDR", "IRR", "IMP",
            "ILS", "JMD", "JPY", "JEP", "KZT", "KPW", "KRW", "KGS", "LAK", "LVL", "LBP", "LRD", "LTL",
            "MKD", "MYR", "MUR", "MXN", "MNT", "MZN", "NAD", "NPR", "ANG", "NZD", "NIO", "NGN", "NOK",
            "OMR", "PKR", "PAB", "PYG", "PEN", "PHP", "PLN", "QAR", "RON", "RUB", "SHP", "SAR", "RSD",
            "SCR", "SGD", "SBD", "SOS", "ZAR", "LKR", "SEK", "CHF", "SRD", "SYP", "TWD", "THB", "TTD",
            "TRY", "TRL", "TVD", "UAH", "GBP", "USD", "UYU", "UZS", "VEF", "VND", "YER", "ZWD");
    public static List<String> currencyCountry = Arrays.asList("United Arab Emirates dirham", "Afghan afghani", "Albania Lek", "Afghanistan Afghani",
            "Argentina Peso", "Aruba Guilder", "Australia Dollar", "Azerbaijan New Manat",
            "Bahamas Dollar", "Barbados Dollar", "Bangladeshi taka", "Belarus Ruble", "Belize Dollar",
            "Bermuda Dollar", "Bolivia Boliviano", "Bosnia and Herzegovina Convertible Marka",
            "Botswana Pula", "Bulgaria Lev", "Brazil Real", "Brunei Darussalam Dollar", "Cambodia Riel",
            "Canada Dollar", "Cayman Islands Dollar", "Chile Peso", "China Yuan Renminbi",
            "Colombia Peso", "Costa Rica Colon", "Croatia Kuna", "Cuba Peso", "Czech Republic Koruna",
            "Denmark Krone", "Dominican Republic Peso", "East Caribbean Dollar", "Egypt Pound",
            "El Salvador Colon", "Estonia Kroon", "Euro Member Countries",
            "Falkland Islands (Malvinas); Pound", "Fiji Dollar", "Ghana Cedis", "Gibraltar Pound",
            "Guatemala Quetzal", "Guernsey Pound", "Guyana Dollar", "Honduras Lempira",
            "Hong Kong Dollar", "Hungary Forint", "Iceland Krona", "India Rupee", "Indonesia Rupiah",
            "Iran Rial", "Isle of Man Pound", "Israel Shekel", "Jamaica Dollar", "Japan Yen",
            "Jersey Pound", "Kazakhstan Tenge", "Korea  North Won", "Korea South Won", "Kyrgyzstan Som",
            "Laos Kip", "Latvia Lat", "Lebanon Pound", "Liberia Dollar", "Lithuania Litas",
            "Macedonia Denar", "Malaysia Ringgit", "Mauritius Rupee", "Mexico Peso", "Mongolia Tughrik",
            "Mozambique Metical", "Namibia Dollar", "Nepal Rupee", "Netherlands Antilles Guilder",
            "New Zealand Dollar", "Nicaragua Cordoba", "Nigeria Naira", "Norway Krone", "Oman Rial",
            "Pakistan Rupee", "Panama Balboa", "Paraguay Guarani", "Peru Nuevo Sol", "Philippines Peso",
            "Poland Zloty", "Qatar Riyal", "Romania New Leu", "Russia Ruble", "Saint Helena Pound",
            "Saudi Arabia Riyal", "Serbia Dinar", "Seychelles Rupee", "Singapore Dollar",
            "Solomon Islands Dollar", "Somalia Shilling", "South Africa Rand", "Sri Lanka Rupee",
            "Sweden Krona", "Switzerland Franc", "Suriname Dollar", "Syria Pound", "Taiwan New Dollar",
            "Thailand Baht", "Trinidad and Tobago Dollar", "Turkey Lira", "Turkey Lira", "Tuvalu Dollar",
            "Ukraine Hryvna", "United Kingdom Pound", "United States Dollar", "Uruguay Peso",
            "Uzbekistan Som", "Venezuela Bolivar", "Viet Nam Dong","Yemen Rial", "Zimbabwe Dollar");

    public static  List<String> ShortCommon  = Arrays.asList("bro", "mom", "vip", "3d", "ID", "I.Q", "DIY", "T.G.I.F", "R.I.P", "KIT", "POV", "ASAP", "FYI",
            "YTD", "OT", "NDA", "B2B", "B2C", "HR", "PR", "CEO", "CFO", "CTO", "VP", "MBA", "CPA", "OMG",
            "NSFW", "TBH", "IMHO", "BRB", "TTYL", "BTW", "BC", "PM", "etc", "RSVP", "ATM", "AKA", "IQ",
            "e.g", "PIN", "www", "ISP", "CD", "OS", "CPU", "I/O", "PC", "IP", "CEO", "MGR", "DEPT", "ASST",
            "DIR", "ACCT", "V.P");
    public static List<String> Commons  = Arrays.asList("brother", "mother", "very important person", "3-dimensional", "identification",
            "Intelligence quotient", "do-it-yourself", "thanks God its friday", "rest in peace", "keep in touch",
            "point of view", "as soon as possible", "for your information", "Year-to-date", "OverTime",
            "Non-disclosure agreement", "business to business", "business to consumer", "Human Resources",
            "public relations", "Cheif executive officer", "Cheif financial officer", "Cheif technology officer",
            "Vice president", "masters of business administration", "certified public accountanty", "oh my God",
            "Not safe for work", "to be honest", "in my honest opinion", "be right back", "talk to you later",
            "by the way", "befor Christ", "prime minister", "et cetera", "please respond",
            "automated teller machine", "also know as", "intelligence quotient", "for example",
            "personal identification number", "world wide web", "internet server Provider", "Compact Disk",
            "operation System", "central operation system", "input/output", "personal computer",
            "internet protocol", "Cheif executive officer", "manager", "department", "association", "director",
            "account", "vice-president");

    public static List<String> country= Arrays.asList("North Atlantic Treaty Organization", "nato", "afghanistan", "af", "albania", "al", "algeria", "dz",
            "american samoa", "as", "andorra", "ad", "angola", "ao", "anguilla", "ai", "antarctica", "aq",
            "antigua and barbuda", "ag", "argentina", "ar", "armenia", "am", "aruba", "aw", "australia", "au",
            "austria", "at", "azerbaijan", "az", "bahamas", "bs", "bahrain", "bh", "bangladesh", "bd",
            "barbados", "bb", "belarus", "by", "belgium", "be", "belize", "bz", "benin", "bj", "bermuda", "bm",
            "bhutan", "bt", "bolivia", "bo", "bosnia and herzegovina", "ba", "botswana", "bw", "bouvet island",
            "bv", "brazil", "br", "british indian ocean territory", "io", "brunei darussalam", "bn", "bulgaria",
            "bg", "burkina faso", "bf", "burundi", "bi", "cambodia", "kh", "cameroon", "cm", "canada", "ca",
            "cape verde", "cv", "cayman islands", "ky", "central african republic", "cf", "chad", "td", "chile",
            "cl", "china", "cn", "christmas island", "cx", "cocos islands", "cc", "colombia", "co", "comoros",
            "km", "congo", "cg", "democratic", "cd", "cook islands", "ck", "costa rica", "cr", "cote divoire",
            "ci", "croatia", "hr", "cuba", "cu", "cyprus", "cy", "czech", "cz", "denmark", "dk", "djibouti",
            "dj", "dominica", "dm", "dominican", "do", "east timor", "tp", "ecuador", "ec", "egypt", "eg",
            "el salvador", "sv", "equatorial guinea", "gq", "eritrea", "er", "estonia", "ee", "ethiopia", "et",
            "falkland islands", "fk", "faroe islands", "fo", "fiji", "fj", "finland", "fi", "france", "fr",
            "french guiana", "gf", "french polynesia", "pf", "french southern territories", "tf", "gabon", "ga",
            "gambia", "gm", "georgia", "ge", "germany", "de", "ghana", "gh", "gibraltar", "gi", "greece", "gr",
            "greenland", "gl", "grenada", "gd", "guadeloupe", "gp", "guam", "gu", "guatemala", "gt", "guinea",
            "gn", "guinea-bissau", "gw", "guyana", "gy", "haiti", "ht", "heard mcdonald islands", "hm",
            "holy see", "va", "honduras", "hn", "hong kong", "hk", "hungary", "hu", "iceland", "is", "india",
            "in", "indonesia", "id", "iran islamic republic", "ir", "iraq", "iq", "ireland", "ie", "israel",
            "il", "italy", "it", "jamaica", "jm", "japan", "jp", "jordan", "jo", "kazakstan", "kz", "kenya",
            "ke", "kiribati", "ki", "korea democratic peoples republic", "kp", "korea republic", "kr", "kuwait",
            "kw", "kyrgyzstan", "kg", "lao peoples democratic republic", "la", "latvia", "lv", "lebanon", "lb",
            "lesotho", "ls", "liberia", "lr", "libyan arab jamahiriya", "ly", "liechtenstein", "li", "lithuania",
            "lt", "luxembourg", "lu", "macau", "mo", "macedonia the former yugoslav republic", "mk",
            "madagascar", "mg", "malawi", "mw", "malaysia", "my", "maldives", "mv", "mali", "ml", "malta", "mt",
            "marshall islands", "mh", "martinique", "mq", "mauritania", "mr", "mauritius", "mu", "mayotte", "yt",
            "mexico", "mx", "micronesia federated states", "fm", "moldova republic", "md", "monaco", "mc",
            "mongolia", "mn", "montserrat", "ms", "morocco", "ma", "mozambique", "mz", "myanmar", "mm",
            "namibia", "na", "nauru", "nr", "nepal", "np", "netherlands", "nl", "netherlands antilles", "an",
            "new caledonia", "nc", "new zealand", "nz", "nicaragua", "ni", "niger", "ne", "nigeria", "ng",
            "niue", "nu", "norfolk island", "nf", "northern mariana islands", "mp", "norway", "no", "oman", "om",
            "pakistan", "pk", "palau", "pw", "palestinian territory occupied", "ps", "panama", "pa",
            "papua new guinea", "pg", "paraguay", "py", "peru", "pe", "philippines", "ph", "pitcairn", "pn",
            "poland", "pl", "portugal", "pt", "puerto rico", "pr", "qatar", "qa", "reunion", "re", "romania",
            "ro", "russian federation", "ru", "rwanda", "rw", "saint helena", "sh", "saint kitts and nevis",
            "kn", "saint lucia", "lc", "saint pierre and miquelon", "pm", "saint vincent and the grenadines",
            "vc", "samoa", "ws", "san marino", "sm", "sao tome and principe", "st", "saudi arabia", "sa",
            "senegal", "sn", "seychelles", "sc", "sierra leone", "sl", "singapore", "sg", "slovakia", "sk",
            "slovenia", "si", "solomon islands", "sb", "somalia", "so", "south africa", "za",
            "south georgia and the south sandwich islands", "gs", "spain", "es", "srilanka", "lk", "sudan", "sd",
            "suriname", "sr", "svalbard and jan mayen", "sj", "swaziland", "sz", "sweden", "se", "switzerland",
            "ch", "syrian arab republic", "sy", "taiwan province of china", "tw", "tajikistan", "tj",
            "tanzania united republic", "tz", "thailand", "th", "togo", "tg", "tokelau", "tk", "tonga", "to",
            "trinidad and tobago", "tt", "tunisia", "tn", "turkey", "tr", "turkmenistan", "tm",
            "turks and caicos islands", "tc", "tuvalu", "tv", "uganda", "ug", "ukraine", "ua",
            "united arab emirates", "ae", "united kingdom", "uk", "united states", "usa","united states amrican", "usa",
            "united states minor outlying islands", "um", "uruguay", "uy", "uzbekistan", "uz", "vanuatu", "vu",
            "venezuela", "ve", "vietnam", "vn", "virgin islands british", "vg", "virgin islands us", "vi",
            "wallis and futuna", "wf", "western sahara", "eh", "yemen", "ye", "yugoslavia", "yu", "zambia", "zm",
            "zimbabwe", "zw", "Overseas Private Investment Corporation", "opic", "United Nations", "un",
            "United Nations Educational Scientific and Cultural Organization", "unesco",
            "United Nations Childrens Emergency Fund", "unicef");

}
